apiVersion: v1
kind: Service
metadata:
  name: salaka-portfolio-svc
  namespace: salaka-portfolio
spec:
  selector:
    app: salaka-portfolio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP